title: One Big Bot
description: My Personal Stack Problems
author: Winfred Selwyn Ooh
github: https://github.com/saintograph
about: Software Engineer and triathlete. Lead developer at OneRelief.
disqus_shortname: saintograph
# google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/
w
social:
    # - icon: fa-facebook
    #   link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/saintograph"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/winfredselwyn"
    # - icon: fa-stack-exchange
    #   link: "#"
    - icon: fa-github
      link: "https://github.com/saintograph"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Work
      url: /projects/
    # - text: XML Feed
    #   url: /feed.xml

url: "https://onebigbot.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
